package formularios;

import formularios.volumen.frm_cilindro_volumen;
import formularios.volumen.frm_cubo_volumen;
import formularios.volumen.frm_esfera_volumen;
import formularios.volumen.frm_paralelepipedo_volumen;
import formularios.volumen.frm_piramide_volumen;

/**
 * IPEC Santo Domingo de Heredia
 * Informática en Desarrollo de Software
 * Proyecto Figuras Geométricas
 * Date: 2021-mar
 * @author  Jesús Alberto Moscoso Agüero
 * @author  J. Mosro - jmosro.14@gmail.com
 * @version 1
*/
public class frm_volumen extends javax.swing.JFrame {

    frm_principal principal_formulario;
    
    public frm_volumen(frm_principal principal) {
        principal_formulario = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cubo = new javax.swing.JButton();
        btn_esfera = new javax.swing.JButton();
        btn_piramide = new javax.swing.JButton();
        btn_cilindro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        btn_paralelepipedo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Geometría");
        setBackground(new java.awt.Color(153, 153, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Volumen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cubo.setBackground(new java.awt.Color(102, 0, 0));
        btn_cubo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cubo.setForeground(new java.awt.Color(255, 255, 255));
        btn_cubo.setText("Cubo");
        btn_cubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuboActionPerformed(evt);
            }
        });

        btn_esfera.setBackground(new java.awt.Color(102, 0, 0));
        btn_esfera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_esfera.setForeground(new java.awt.Color(255, 255, 255));
        btn_esfera.setText("Esfera");
        btn_esfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esferaActionPerformed(evt);
            }
        });

        btn_piramide.setBackground(new java.awt.Color(102, 0, 0));
        btn_piramide.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_piramide.setForeground(new java.awt.Color(255, 255, 255));
        btn_piramide.setText("Pirámide");
        btn_piramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_piramideActionPerformed(evt);
            }
        });

        btn_cilindro.setBackground(new java.awt.Color(102, 0, 0));
        btn_cilindro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cilindro.setForeground(new java.awt.Color(255, 255, 255));
        btn_cilindro.setText("Cilindro");
        btn_cilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cilindroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Elegir una figura para calcular el volumen");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_anterior.setBackground(new java.awt.Color(102, 102, 0));
        btn_anterior.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_anterior.setForeground(new java.awt.Color(255, 255, 255));
        btn_anterior.setText("Anterior");
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_paralelepipedo.setBackground(new java.awt.Color(102, 0, 0));
        btn_paralelepipedo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_paralelepipedo.setForeground(new java.awt.Color(255, 255, 255));
        btn_paralelepipedo.setText("Paralelepípedo");
        btn_paralelepipedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paralelepipedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cilindro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_piramide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_paralelepipedo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_esfera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btn_cilindro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cubo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_esfera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_paralelepipedo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_piramide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_anterior)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuboActionPerformed
        frm_cubo_volumen cubo_volumen = new frm_cubo_volumen(this);
        this.setVisible(false);
        cubo_volumen.setVisible(true);
    }//GEN-LAST:event_btn_cuboActionPerformed

    private void btn_esferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esferaActionPerformed
        frm_esfera_volumen esfera_volumen = new frm_esfera_volumen(this);
        this.setVisible(false);
        esfera_volumen.setVisible(true);
    }//GEN-LAST:event_btn_esferaActionPerformed

    private void btn_piramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_piramideActionPerformed
        frm_piramide_volumen piramide_volumen = new frm_piramide_volumen(this);
        this.setVisible(false);
        piramide_volumen.setVisible(true);
    }//GEN-LAST:event_btn_piramideActionPerformed

    private void btn_cilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cilindroActionPerformed
        frm_cilindro_volumen cilindro_volumen = new frm_cilindro_volumen(this);
        this.setVisible(false);
        cilindro_volumen.setVisible(true);
    }//GEN-LAST:event_btn_cilindroActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        this.dispose();
        //principal_formulario.setVisible(true);
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal_formulario.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_paralelepipedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paralelepipedoActionPerformed
        frm_paralelepipedo_volumen paralelepipedo_volumen = new frm_paralelepipedo_volumen(this);
        this.setVisible(false);
        paralelepipedo_volumen.setVisible(true);
    }//GEN-LAST:event_btn_paralelepipedoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_volumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_volumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_volumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_volumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_volumen(new frm_principal()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_cilindro;
    private javax.swing.JButton btn_cubo;
    private javax.swing.JButton btn_esfera;
    private javax.swing.JButton btn_paralelepipedo;
    private javax.swing.JButton btn_piramide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
